name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same API as Amazon AWS S3.
version: 0.11.10
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  meta: ^1.1.5
  crypto: ^2.0.6
  http_client: ^0.5.0
  xml: ^3.0.1

dev_dependencies:
  test: ^1.0.0
